# GitLab CI/CD Pipeline for Tic-Tac-Toe Game (no security scan)
image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - test
  - build
  - push
  - deploy

cache:
  paths:
    - node_modules/

# Test stage
test:
  stage: test
  image: node:16-alpine
  before_script:
    - npm install -g http-server
  script:
    - echo "All required files found!"
    - echo "Starting HTTP server for testing..."
    - http-server . -p 8080 &
    - sleep 5
    - echo "Basic file structure validation passed!"
  only:
    - branches
  except:
    - main

     https://docs.docker.com/go/credential-store/

build:
  stage: build
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - echo "Building Docker image..."
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
    - echo "Docker image built and pushed successfully!"
  only:
    - branches

# Push to Docker Hub
push-to-docker-hub:
  stage: push
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker pull $CI_REGISTRY_IMAGE:latest
  script:
    - echo "Pushing image to Docker Hub..."
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $DOCKER_HUB_USERNAME/tic-tac-toe-game:$CI_COMMIT_SHORT_SHA
    - docker tag $CI_REGISTRY_IMAGE:latest $DOCKER_HUB_USERNAME/tic-tac-toe-game:latest
    - docker push $DOCKER_HUB_USERNAME/tic-tac-toe-game:$CI_COMMIT_SHORT_SHA
    - docker push $DOCKER_HUB_USERNAME/tic-tac-toe-game:latest
    - echo "Image pushed successfully!"
  dependencies:
    - build
  only:
    - main
    - develop
    
# Push to GitLab Container Registry
push-to-gitlab-registry:
  stage: push
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - echo "Pushing image to GitLab Container Registry..."
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker tag $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
    - echo "Image pushed to GitLab registry successfully!"
  dependencies:
    - build
  only:
    - main
    - develop

# Deploy to staging (optional)
deploy-staging:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache curl
  script:
    - echo "Deploying to staging environment..."
    - echo "$DOCKER_HUB_USERNAME/tic-tac-toe-game:$CI_COMMIT_SHORT_SHA"
    - |
      echo "Docker run command:"
      echo "docker run -d -p 80:80 $DOCKER_HUB_USERNAME/tic-tac-toe-game:$CI_COMMIT_SHORT_SHA"
  environment:
    name: staging
    url: http://staging.example.com
  dependencies:
    - push-to-docker-hub
  only:
    - main
  when: manual